spring.application.name=verify
spring.config.import=optional:file:.env[.properties],optional:file:verify/verify/.env[.properties]

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/verifydb}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:password}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Set this to your local tessdata folder if auto-detection does not work.
# Example: C:/Program Files/Tesseract-OCR/tessdata
tesseract.datapath=D:/ADL/tesseract/tessdata
tesseract.language=eng

management.endpoints.web.exposure.include=info

server.port=8080

