spring.application.name=verify
spring.datasource.url=jdbc:postgresql://ep-lingering-sun-anqfcprj-pooler.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner
spring.datasource.password=npg_ejt2IERVGP6d

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

management.endpoints.web.exposure.include=info

server.port=8080

